function MotorDriveUnit_loadSimulationCase_Drive
%% Sets up simulation
% This function sets up the followings:
% - Simulation stop time
% - Input signals
% - Initial conditions
%
% Model must be loaded for this function to work.

% Copyright 2023 The MathWorks, Inc.

MotorDriveUnit_loadSimulationCase( ...
  CaseName = "Drive motor", ...
  ...
  ModelName = "MotorDriveUnit_harness_model", ...
  ...
  StopTime = 400, ...
  ...
  InputSystemPath = "/Inputs", ...
  ...
  AxleClutchSwitch_BlockName = "Axle clutch switch", ...
  AxleClutchSwitch_DataPoints = [0 0; 1 0], ...
  ...
  AxleSpeed_BlockName = "Axle speed", ... rpm
  AxleSpeed_DataPoints = [0 1 0], ...
  AxleSpeed_DeltaT = 10, ...
  ...
  AxleTorque_BlockName = "Axle torque", ... N*m
  AxleTorque_DataPoints = [0 20 0; 21 300 -10], ...
  AxleTorque_DeltaT = 0.1, ...
  ...
  MotorTorqueCommand_BlockName = "Motor torque command", ... N*m
  MotorTorqueCommand_DataPoints = [0 10 0; 60 100 -300; 105 200 200; 205 300 250 ], ... Driving motor
  MotorTorqueCommand_DeltaT = 0.5, ...
  ...
  HeatFlowCommand_BlockName = "Heat flow command", ... W
  HeatFlowCommand_DataPoints = [0 50 0; 60 200 -2000; 250 300 -12000], ... Cooling motor
  HeatFlowCommand_DeltaT = 1, ...
  ...
  LoadInertia_kg_m2 = 100*0.3^2, ...
  LoadDamping_Nm_per_rpm = 0.03, ...
  ...
  GeartrainInertia_kg_m2 = 15*0.3^2, ...
  GeartrainDamping_Nm_per_rpm = 0.001, ...
  ...
  HVBattery_Voltage_V = 340, ...
  HVBattery_TerminalResistance_Ohm = 0.01, ...
  ...
  Initial_LoadInertiaSpd_rpm = 0, ...
  Initial_MotorDriveUnit_RotorSpd_rpm = 0, ...
  Initial_MotorDriveUnit_Temperature_K = 273.15 + 20, ...
  Initial_AmbientTemperature_K = 273.15 + 20, ...
  ...
  DisplayMessage = true );

end  % function
