function MotorDriveUnit_useRefsub_BasicThermal

% Copyright 2023 The MathWorks, Inc.

MotorDriveUnit_useRefsub( ...
  ModelName = "MotorDriveUnit_harness_model", ...
  BlockPath = "/Motor Drive Unit", ...
  RefsubName    = "MotorDriveUnit_refsub_BasicThermal", ...
  ParamFileName = "MotorDriveUnit_refsub_BasicThermal_params" )

end  % function
