function MotorDriveUnit_loadSimulationCase_Random(nvpairs)
% Sets up simulation
% This function sets up the followings:
% - Simulation stop time
% - Input signals
% - Initial conditions
%
% Model must be loaded for this function to work.

% Copyright 2023 The MathWorks, Inc.

arguments
  nvpairs.RandomSeed (1,1) {mustBePositive} = 543
  nvpairs.NumTransitions (1,1) {mustBePositive} = 20
  nvpairs.InitialSOC_pct (1,1) {mustBeInRange(nvpairs.InitialSOC_pct, 0, 100)} = 60
end

deltaInterp = 0.5;

sigTrqCmd = SignalDesignUtility.buildTrace( ...
  RandomSeed = nvpairs.RandomSeed, ...
  InterpolationStepSize = deltaInterp, ...
  XInitialFlatLength = 5, ... Initial duration for constant torque command
  YInitialValue = 0, ... Initial value of torque command
  NumTransitions  = nvpairs.NumTransitions, ...
  TransitionRange = [2 5], ... Time range of transition from one constant segment to the next
  FlatRange = [3 20], ... Time range of constant segment
  YRange = [0 100], ... Value range of torque command
  XFinalTransitionLength = 2, ... Duration of final transition
  XFinalFlatLength = 10, ... Duration of final constant torque command segment
  YFinalValue = 0 );  % Final torque command value

sigAxleTrq = SignalDesignUtility.buildTrace( ...
  RandomSeed = nvpairs.RandomSeed, ...
  InterpolationStepSize = deltaInterp, ...
  XInitialFlatLength = 5, ... Initial duration for constant axle torque
  YInitialValue = 0, ... Initial value of axle torque
  NumTransitions  = ceil( 3 * nvpairs.NumTransitions ), ...
  TransitionRange = [1 3], ... Time range of transition from one constant segment to the next
  FlatRange = [1 5], ... Time range of constant segment
  YRange = [-10 -3], ... Value range of axle torque
  XFinalTransitionLength = 2, ... Duration of final transition
  XFinalFlatLength = 10, ... Duration of final constant axle torque segment
  YFinalValue = 0 );  % Final axle torque value

t1 = sigTrqCmd.Data.X(end);
t2 = sigAxleTrq.Data.X(end);
if t1 < t2
  t_end = t2;
else
  t_end = t1;
end

% Uncomment below to plot and see the generated signal traces.
%{
fig1 = plotDataPoints(sigTrqCmd);
fig2 = plotDataPoints(sigAxleTrq);
xlim(fig1, [0, t_end])
xlim(fig2, [0, t_end])
return
%}

MotorDriveUnit_loadSimulationCase( ...
  CaseName = "Randomly generated input signals", ...
  ...
  ModelName = "MotorDriveUnit_harness_model", ...
  ...
  StopTime = t_end, ...
  ...
  InputSystemPath = "/Inputs", ...
  ...
  AxleClutchSwitch_BlockName = "Axle clutch switch", ...
  AxleClutchSwitch_DataPoints = [0 0; 1 0], ...
  ...
  AxleSpeed_BlockName = "Axle speed", ... rpm
  AxleSpeed_DataPoints = [0 1 0], ...
  AxleSpeed_DeltaT = 10, ...
  ...
  AxleTorque_BlockName = "Axle torque", ... N*m
  AxleTorque_DataPoints = sigAxleTrq.XYData, ...
  AxleTorque_DeltaT = deltaInterp, ...
  ...
  MotorTorqueCommand_BlockName = "Motor torque command", ... N*m
  MotorTorqueCommand_DataPoints = sigTrqCmd.XYData, ...
  MotorTorqueCommand_DeltaT = deltaInterp, ...
  ...
  HeatFlowCommand_BlockName = "Heat flow command", ... W
  HeatFlowCommand_DataPoints = [0 50 0; 60 200 -100; 210 300 -400], ... Cooling motor
  HeatFlowCommand_DeltaT = 1, ...
  ...
  LoadInertia_kg_m2 = 100*0.3^2, ...
  LoadDamping_Nm_per_rpm = 0.03, ...
  ...
  GeartrainInertia_kg_m2 = 15*0.3^2, ...
  GeartrainDamping_Nm_per_rpm = 0.001, ...
  ...
  HVBattery_Voltage_V = 340, ...
  HVBattery_TerminalResistance_Ohm = 0.01, ...
  ...
  Initial_LoadInertiaSpd_rpm = 0, ...
  Initial_MotorDriveUnit_RotorSpd_rpm = 0, ...
  Initial_MotorDriveUnit_Temperature_K = 273.15 + 20, ...
  Initial_AmbientTemperature_K = 273.15 + 20, ...
  ...
  DisplayMessage = true );

end  % function
