function MotorDriveUnit_useRefsub_Basic

% Copyright 2023 The MathWorks, Inc.

MotorDriveUnit_useRefsub( ...
  ModelName = "MotorDriveUnit_harness_model", ...
  BlockPath = "/Motor Drive Unit", ...
  RefsubName    = "MotorDriveUnit_refsub_Basic", ...
  ParamFileName = "MotorDriveUnit_refsub_Basic_params" )

end  % function
