function MotorDriveUnit_useRefsub_SystemTable

% Copyright 2023 The MathWorks, Inc.

MotorDriveUnit_useRefsub( ...
  ModelName = "MotorDriveUnit_harness_model", ...
  BlockPath = "/Motor Drive Unit", ...
  RefsubName    = "MotorDriveUnit_refsub_SystemTable", ...
  ParamFileName = "MotorDriveUnit_refsub_SystemTable_params" )

end  % function
