function MotorDriveUnit_useRefsub_System

% Copyright 2023 The MathWorks, Inc.

MotorDriveUnit_useRefsub( ...
  ModelName = "MotorDriveUnit_harness_model", ...
  BlockPath = "/Motor Drive Unit", ...
  RefsubName    = "MotorDriveUnit_refsub_System", ...
  ParamFileName = "MotorDriveUnit_refsub_System_params" )

end  % function
