function CommandText = buildSearchCommandText(NameValuePair)

% Copyright 2025 The MathWorks, Inc.

arguments (Input)
  NameValuePair.BuildFrom (1,1) string {mustBeMember(NameValuePair.BuildFrom, ["SearchOptions", "ResultTable"])} = "SearchOptions"

  NameValuePair.ResultTable {TextSearchTool1.mustBeTextSearchTable} = TextSearchTool1.newTextSearchTable

  % ---

  NameValuePair.TargetFolder (:,1) string = pwd
  NameValuePair.IncludeSubfolders (1,1) logical = false

  NameValuePair.FileTypes (1,:) string = ["*.m", "*.mdl"]
  NameValuePair.Filter (1,:) {CodeTool1.mustBeFunctionHandleOrEmpty} = []
  NameValuePair.ExcludeLiveScript (1,1) logical = false
  NameValuePair.ExcludeMATLABCodeFile (1,1) logical = false

  NameValuePair.TextPattern (1,1) pattern = alphanumericBoundary + "Copyright" + alphanumericBoundary
  NameValuePair.IgnoreCase (1,1) logical = false
  NameValuePair.MatchWholeWord (1,1) logical = false

  NameValuePair.IncludeStyledFilePath (1,1) logical = false

end  % arguments

arguments (Output)
  CommandText (1,1) string
end  % arguments

if NameValuePair.BuildFrom == "ResultTable"

  p = NameValuePair.ResultTable.Properties.CustomProperties;

  CommandText = ...
    "TextSearchTool1.searchText(" + ...
    "TargetFolder=""" + p.TargetFolder + """, " + ...
    "IncludeSubfolders=" + string(p.IncludeSubfolders) + ", " + ...
    "FileTypes=[""" + join(p.FileTypes, """, """) + """], " + ...
    "ExcludeLiveScript=" + string(p.ExcludeLiveScript) + ", " + ...
    "ExcludeMATLABCodeFile=" + string(p.ExcludeMATLABCodeFile) + ", " + ...
    "TextPattern=(" + string(p.TextPattern) + "), " + ...
    "IgnoreCase=" + string(p.IgnoreCase) + ", " + ...
    "MatchWholeWord=" + string(p.MatchWholeWord) + ", " + ...
    "IncludeStyledFilePath=" + string(p.IncludeStyledFilePath) + ")";

else
  CommandText = ...
    "TextSearchTool1.searchText(" + ...
    "TargetFolder=""" + NameValuePair.TargetFolder + """, " + ...
    "IncludeSubfolders=" + string(NameValuePair.IncludeSubfolders) + ", " + ...
    "FileTypes=[""" + join(NameValuePair.FileTypes, """, """) + """], " + ...
    "ExcludeLiveScript=" + string(NameValuePair.ExcludeLiveScript) + ", " + ...
    "ExcludeMATLABCodeFile=" + string(NameValuePair.ExcludeMATLABCodeFile) + ", " + ...
    "TextPattern=(" + string(NameValuePair.TextPattern) + "), " + ...
    "IgnoreCase=" + string(NameValuePair.IgnoreCase) + ", " + ...
    "MatchWholeWord=" + string(NameValuePair.MatchWholeWord) + ", " + ...
    "IncludeStyledFilePath=" + string(NameValuePair.IncludeStyledFilePath) + ")";

end  % if
end  % function
