function fig = plotElevationAndRoadGradeProfiles(NameValuePair)
% Make plots of elevation profile and road grade profile.
%
% This function optionally plots the original road grade data if
% the following conditions are met.
%
% 1) PlotCoarseData option is set to true.
%
% 2) The custom properties of the ProfileTable were created by
%    the buildElevationProfileFromRoadGradeProfileBlock function.

% Copyright 2026 The MathWorks, Inc.

arguments (Input)
  NameValuePair.ParentAxes matlab.graphics.axis.Axes {mustBeScalarOrEmpty}

  % ThemeMode and Theme are valid only when 1) MATLAB is R2025a or newer and 2) ParentAxes is not specified.
  % Theme is ignored if ThemeMode is "auto".
  % These options correspond to the figure's equivalent options.
  % https://www.mathworks.com/help/matlab/ref/matlab.ui.figure.html
  NameValuePair.ThemeMode {mustBeMember(NameValuePair.ThemeMode, ["auto", "manual"])} = "auto"
  NameValuePair.Theme {mustBeMember(NameValuePair.Theme, ["light", "dark"])} = "light"

  % Refined data were generated by interpolating the base data.
  % Use this option to plot the base data or not.
  NameValuePair.PlotBaseData (1,1) logical = true

  % ProfileTable is ignored if DataSource is "direct".
  NameValuePair.DataSource (1,1) string {mustBeMember(NameValuePair.DataSource, ["direct", "table"])} = "direct"

  % ---------------------------------------------------------------------------
  % Options for DataSource="direct"

  NameValuePair.BaseHorizontalDistance (1,:) {mustBeA(NameValuePair.BaseHorizontalDistance, ["double", "simscape.Value"])} = [-1 0 1]
  NameValuePair.BaseGradePercent (1,:) double = [-1 -1 -1]

  NameValuePair.RefinedHorizontalDistance (1,:) {mustBeA(NameValuePair.RefinedHorizontalDistance, ["double", "simscape.Value"])} = [-1 0 1]
  NameValuePair.RefinedGradePercent (1,:) double = [-1 -1 -1]
  NameValuePair.RefinedElevation (1,:) {mustBeA(NameValuePair.RefinedElevation, ["double", "simscape.Value"])} = [1 0 -1]

  % ---------------------------------------------------------------------------
  % Options for DataSource="table"

  NameValuePair.ProfileTable (:,3) table ...
    = table(simscape.Value([-1; 0; 1], "m"), [0; 0; 0], simscape.Value([0; 0; 0], "m"), ...
    VariableNames = ["HorizontalDistance", "GradePercent", "Elevation"])

end  % arguments

arguments (Output)
  fig {mustBeScalarOrEmpty, mustBeA(fig, ["matlab.ui.Figure", "matlab.graphics.layout.TiledChartLayout"])}
end  % arguments

plot_base_data = NameValuePair.PlotBaseData;

if NameValuePair.DataSource == "direct"
  if class(NameValuePair.RefinedHorizontalDistance) == "simscape.Value"
    refined_x_vec_value = value(NameValuePair.RefinedHorizontalDistance);
    refined_x_vec_unit = string(unit(NameValuePair.RefinedHorizontalDistance));
  else
    refined_x_vec_value = NameValuePair.RefinedHorizontalDistance;
    refined_x_vec_unit = "";
  end  % if

  refined_grade_pct = NameValuePair.RefinedGradePercent;

  if class(NameValuePair.RefinedElevation) == "simscape.Value"
    refined_elevation_value = value(NameValuePair.RefinedElevation);
    refined_elevation_unit = string(unit(NameValuePair.RefinedElevation));
  else
    refined_elevation_value = NameValuePair.RefinedElevation;
    refined_elevation_unit = "";
  end  % if

  if class(NameValuePair.BaseHorizontalDistance) == "simscape.Value"
    % Get the value of base_x_vec in the unit of refined_x_vec.
    base_x_vec_value = value(NameValuePair.BaseHorizontalDistance, refined_x_vec_unit);
  else
    base_x_vec_value = NameValuePair.BaseHorizontalDistance;
  end  % if

  base_grade_pct = NameValuePair.BaseGradePercent;

else
  % Data source is "table".
  tbl = NameValuePair.ProfileTable;

  refined_x_vec_ssc = tbl.HorizontalDistance;
  refined_x_vec_value = value(refined_x_vec_ssc);
  refined_x_vec_unit = string(unit(refined_x_vec_ssc));

  refined_grade_pct = tbl.GradePercent;

  refined_elevation_ssc = tbl.Elevation;
  refined_elevation_value = value(refined_elevation_ssc);
  refined_elevation_unit = string(unit(refined_elevation_ssc));

  if isempty(fieldnames(tbl.Properties.CustomProperties))
    plot_base_data = false;

  else
    prop = tbl.Properties.CustomProperties;

    base_x_vec_ssc = simscape.Value(prop.HorizontalDistance_value, prop.HorizontalDistance_unit);
    % Get the value of base_x_vec in the unit of refined_x_vec.
    base_x_vec_value = value(base_x_vec_ssc, refined_x_vec_unit);

    base_grade_pct = prop.RoadGradePercent;
  end  % if

end  % if

if isfield(NameValuePair, "ParentAxes")
  % NameValuePair.ParentAxes is guaranteed to be of type matlab.graphics.axis.Axes.
  ax = NameValuePair.ParentAxes;
  tl = tiledlayout(ax.Parent, 2, 1, TileSpacing="tight");
else
  fig = figure(WindowStyle="normal");
  if not(isMATLABReleaseOlderThan("R2025a"))
    fig.Theme = NameValuePair.Theme;
    fig.ThemeMode = NameValuePair.ThemeMode;
  end  % if
  tl = tiledlayout(fig, 2, 1, TileSpacing="tight");
end  % if

ax = nexttile(tl);
plot(ax, refined_x_vec_value, refined_elevation_value, LineWidth=2)
hold(ax, "on")
grid(ax, "on")
axis(ax, "padded")
title(ax, "Elevation")
if refined_elevation_unit ~= ""
  ylabel(ax, refined_elevation_unit, Interpreter="latex")
end  % if

ax = nexttile(tl);
plot(ax, refined_x_vec_value, refined_grade_pct, LineWidth=2)
hold(ax, "on")
grid(ax, "on")
axis(ax, "padded")
if plot_base_data
  sc = scatter(ax, base_x_vec_value, base_grade_pct, 60);
  sc.Marker = "x";
  sc.LineWidth = 1.4;
end  % if
title(ax, "Road grade")
ylabel(ax, "\%", Interpreter="latex")

if refined_x_vec_unit == ""
  xlabel(ax, "Horizontal position $x$", Interpreter="latex")
else
  xlabel(ax, "Horizontal position $x$ (" + refined_x_vec_unit + ")", Interpreter="latex")
end  % if

if nargout == 0
  clear fig
end  % if
end  % function
