%% Parameters for the BEV Controller test inputs
% If you edit this file, make sure to run this script to update the variable
% in the base workspace before running simulation.

% Copyright 2025-2026 The MathWorks, Inc.

signal_design_matrix = bevutil1.SignalUtil.generateSignalDesignMatrixFromTraceProperties(...
  RandomSeed = 25, ...
  FInitialValue = 0, ...
  XInitialFlatLength = 100, ...
  XInitialTransitionLength = 20, ...
  NumTransitions = 10, ...
  TransitionXRange = [1 10], ...
  FlatXRange = [10 300], ...
  FRange = [40 100], ...
  XFinalTransitionLength = 20, ...
  XFinalFlatLength = 10, ...
  FFinalValue = 0 );

vectors = bevutil1.SignalUtil.getVectorsFromSignalDesignMatrix(signal_design_matrix);

% Use this table in a lookup table block.
% Table data are used as the parameters of a lookup table block which requires at least three data points.
VehicleSpeedInput = table( ...
  simscape.Value(vectors.X, "s"), ...
  simscape.Value(vectors.F, "km/hr"), ...
  VariableNames=["Time", "Speed"]);
