%% Load input signal data in the base workspace
% Lookup table blocks should refer to the base workspace variables that are defined in this script.

% Copyright 2026 The MathWorks, Inc.

% Use Simscape's unit of time with a table, instead of a duration object and a timetable.
% This approach makes it consistent to handle units in block parameters.

%% Axle speed input clutch on/off
% Discrete signal
Time = simscape.Value([0 1]', "s");
StepValues = [0 0]';
MDU_HarnessInputs.AxleSpeedSwitch = table(Time, StepValues);

%% Axle speed
% Akima spline (in the lookup table block) requires at least three data points.
Time = simscape.Value([0 1 2]', "s");
Data = simscape.Value([0 0 0]', "rpm");
MDU_HarnessInputs.AxleSpeed = table(Time, Data);

%% Axle torque
% Akima spline (used in the lookup table block) requires at least three data points.

signal_design_matrix = bevutil1.SignalUtil.generateSignalDesignMatrixFromTraceProperties(...
  RandomSeed = 543, ...
  FInitialValue = 0, ...
  XInitialFlatLength = 5, ...
  XInitialTransitionLength = 5, ...
  NumTransitions = 60, ...
  TransitionXRange = [1 3], ...
  FlatXRange = [1 5], ...
  FRange = [-10 -3], ...
  XFinalTransitionLength = 2, ...
  XFinalFlatLength = 10, ...
  FFinalValue = 0 );

data_table = bevutil1.SignalUtil.getVectorsFromSignalDesignMatrix(signal_design_matrix);
Time = simscape.Value(data_table.X, "s");
Data = simscape.Value(data_table.F, "N*m");
MDU_HarnessInputs.AxleTorque = table(Time, Data);

%% Motor torque command
% Akima spline (used in the lookup table block) requires at least three data points.

signal_design_matrix = bevutil1.SignalUtil.generateSignalDesignMatrixFromTraceProperties(...
  RandomSeed = 543, ...
  FInitialValue = 0, ...
  XInitialFlatLength = 5, ...
  XInitialTransitionLength = 5, ...
  NumTransitions = 20, ...
  TransitionXRange = [2 5], ...
  FlatXRange = [3 20], ...
  FRange = [0 100], ...
  XFinalTransitionLength = 2, ...
  XFinalFlatLength = 10, ...
  FFinalValue = 0 );

data_table = bevutil1.SignalUtil.getVectorsFromSignalDesignMatrix(signal_design_matrix);
Time = simscape.Value(data_table.X, "s");
Data = simscape.Value(data_table.F, "N*m");
MDU_HarnessInputs.MotorTorqueCommand = table(Time, Data);

%% Motor heat flow
% Akima spline (in the lookup table block) requires at least three data points.
Time = simscape.Value([0 1 2]', "s");
Data = simscape.Value([0 0 0]', "W");
MDU_HarnessInputs.MotorHeatFlow = table(Time, Data);
