function CoverageSummary = summarizeCodeCoverage(CodeCoverageFile)
% Summarize code coverage information from a Cobertura XML coverage file.
%
% This function takes an XML file in Cobertura format which was generated by
% the Build Tool.
% The coverage handled in this function is statement coverage (C0 coverage.)
%
% See also:
%
% matlab.unittest.plugins.CodeCoveragePlugin Class
% https://www.mathworks.com/help/matlab/ref/matlab.unittest.plugins.codecoverageplugin-class.html
%
% matlab.coverage.Result Class
% https://www.mathworks.com/help/matlab/ref/matlab.coverage.result-class.html
%
% generateCoberturaReport
% https://www.mathworks.com/help/matlab/ref/matlab.coverage.result.generatecoberturareport.html
%
% matlab.buildtool.tasks.TestTask Class, CodeCoverageResults
% https://uk.mathworks.com/help/matlab/ref/matlab.buildtool.tasks.testtask-class.html

% !todo: Support exclusion list to eliminate files like "buildfile.m" and folders like "sample folder" from the coverage analysis.

% Example Cobertura XML contents
%{
<?xml ...>
<coverage ...>
  <sources>
    <source>C:\path\to\a\folder\</source>
  </sources>
  <packages>
    ...
    <package ... line-rate="0.87" name="AppUtil.Component"> ===> A <package> with a non-empty name corresponds to a MATLAB name space.
      ...
    </package>
    <package ... line-rate="0.87" name="AppUtil.Graphics">
      <classes>
        <class ... filename="AppUtil\+bev1mus\+AppUti\+Graphics\Axes.m" line-rate="0.98" name="bev1mus.AppUtil.Graphics.Axes">
          <methods>
            <method ... name="setup" signature="setup(component)">
              <lines>
                <line hits="30" number="30"/>
                <line hits="30" number="32"/>
                <line hits="30" number="33"/>
                ...
              </lines>
            </method>
            <method ... name="update" signature="update(component)">
              <lines>
                <line hits="58" number="47"/>
                <line hits="58" number="49"/>
                <line hits="2" number="56"/>
                ...
            </method>
          </methods>
          <lines> ===> Repeating the info under the <methods>. Safe to ignore.
            <line hits="30" number="30"/>
            <line hits="30" number="32"/>
            ...
          </lines>
        </class>
        ...
      </classes>
    </package>
    ...
    <package ... line-rate="0.87" name=""> ===> A <package> with an empty name corresponds to files outside MATLAB name spaces.
      <classes>
        <class filename="AppUtil\CodeCoverageApp_AppUtil.m" line-rate="0.54" name="CodeCoverageApp_AppUtil">
          <methods/> ===> <methods/> indicates that the file is a function, not a class.
          <lines>
            <line hits="1" number="10"/>
            <line hits="1" number="12"/>
            <line hits="1" number="13"/>
            ...
          </lines>
        </class>
        <class filename="AppUtil\ColorMapApp.m" line-rate="0.88" name="ColorMapApp">
          <methods/>
          <lines>
            ...
          </lines>
        </class>
        ...
        <class ... filename="AppUtil\Test\Button\uitest_Button.m" line-rate="0.93151" name="uitest_Button">
          <methods>
            <method ... line-rate="0.88889" name="test_method_setup" signature="test_method_setup(testcase)"> ===> This corresponds to a class method/function.
              <lines>
                <line hits="13" number="27"/>
                <line hits="13" number="28"/>
                <line hits="0" number="31"/>
                ...
              </lines>
            </method>
            ...
          </methods>
        </class>
        ...
        ... ===> There can be many <class>...</class> for MATLAB code files.
        ...
    </package>
    ...
  </packages>
</coverage>
%}

% Copyright 2025-2026 The MathWorks, Inc.

arguments (Input)
  CodeCoverageFile (1,1) string {mustBeFile}
end  % arguments

arguments (Output)
  CoverageSummary struct
end  % arguments

cov_struct = readstruct(CodeCoverageFile);

% -----------------------------------------------------------------------------
% Top-level coverage

% In the code coverage file, attribute values are double-quoted text. However,
% the "*Attribute" values generated by readstruct for line-rate, line-covered,
% lines-valid, and timestamp are numeric values.
line_rate = cov_struct.line_rateAttribute;
StatementCoveragePercent = line_rate * 100;
LinesCovered = cov_struct.lines_coveredAttribute;
LinesValid = cov_struct.lines_validAttribute;
time_stamp_posix = cov_struct.timestampAttribute;
TimeStamp = "UTC " + string(datetime(time_stamp_posix, ConvertFrom="posixtime", TimeZone="UTC", Format="yyyy-MM-dd HH:mm:ss"));

total_cov_table = table(StatementCoveragePercent, LinesCovered, LinesValid, TimeStamp);

top_folder = cov_struct.sources.source;

total_cov_table = addprop(total_cov_table, "TopFolder", "table");
total_cov_table.Properties.CustomProperties.TopFolder = top_folder;

CoverageSummary = struct;
CoverageSummary.TotalCoverageTable = total_cov_table;

% -----------------------------------------------------------------------------
% Component-level coverage
% Coverage within MATLAB name spaces

cov_packages = cov_struct.packages.package;
num_packages = numel(cov_packages);

% [cov_packages.nameAttribute] is an array of MATLAB name spaces.
% The package with an empty name attribute, i.e., name="" in XML, is for files outside MATLAB name spaces.
% There must be only 1 package which has an empty name attribute.
empty_package_name_index = ([cov_packages.nameAttribute] == "");
assert(nnz(empty_package_name_index) == 1)

num_namespace_targets = nnz(~empty_package_name_index);
ComponentName = strings(num_namespace_targets, 1);
ComponentCoveragePercent = nan(num_namespace_targets, 1);
cnt1 = 0;
for pp = 1 : num_packages
  current_package = cov_packages(pp);
  if current_package.nameAttribute == ""
    % The package is not within MATLAB name space.

    continue

  end  % for
  cnt1 = cnt1 + 1;
  ComponentName(cnt1) = current_package.nameAttribute;
  ComponentCoveragePercent(cnt1) = current_package.line_rateAttribute * 100;
end  % for

component_cov_table = table(ComponentName, ComponentCoveragePercent);
component_cov_table = sortrows(component_cov_table, 'ComponentName');

CoverageSummary.ComponentCoverageTable = component_cov_table;

% -----------------------------------------------------------------------------
% File-level coverage
% Statement coverage (C0 coverage) information of individual files.

target_classes = cov_packages(empty_package_name_index).classes.class;

num_file_targets = numel(target_classes);

TestClassName = strings(num_file_targets, 1);
FilePath = strings(num_file_targets, 1);
StatementCoveragePercent = nan(num_file_targets, 1);

for cc = 1 : num_file_targets
  current_class = target_classes(cc);
  TestClassName(cc) = current_class.nameAttribute;
  FilePath(cc) = current_class.filenameAttribute;
  line_rate = current_class.line_rateAttribute;
  StatementCoveragePercent(cc) = line_rate * 100;
end  % for

file_cov_table = table(StatementCoveragePercent, TestClassName, FilePath);
file_cov_table = sortrows(file_cov_table, {'StatementCoveragePercent', 'FilePath'});

CoverageSummary.FileCoverageTable = file_cov_table;

end  % function
