function VehSpdRef_setSimCase_HighSpeed(NameValuePair)
%% Sets up simulation
% Model must be loaded for this function to work.

% Copyright 2023 The MathWorks, Inc.

arguments
  NameValuePair.ModelName {mustBeTextScalar} = "VehSpdRef_TestModel"
  NameValuePair.TargetSubsystemPath {mustBeTextScalar} = "/Vehicle speed reference"
  NameValuePair.DisplayMessage (1,1) logical = true
end

VehSpdRef_setSimCase( ...
  CaseName = "High speed driving", ...
  CaseNumber = 2, ...
  StopTime = 200, ...
  ...
  ModelName = NameValuePair.ModelName, ...
  TargetSubsystemPath = NameValuePair.TargetSubsystemPath, ...
  DisplayMessage = NameValuePair.DisplayMessage )

end  % function
