%[text] # searchAndReplaceText demo
%[text] For the result from a dry run, the `NumReplacedLines` column indicates the number of lines which would have been replaced if not dry run.
result = TextSearchTool1.searchAndReplaceText(...
  DryRun = true, ...
  TargetFolder = pwd, ...
  IncludeSubfolders = false, ...
  FileTypes = ["*.m", "*.md"], ...
  TextPattern = "Copyright", ...
  NewText = "Copyleft" );

disp(result.Properties.CustomProperties.TargetFolder) %[output:3a046336]
disp(result) %[output:82c1d475]
%%
%[text] Use the Filter option to apply an additional file filter.
result = TextSearchTool1.searchAndReplaceText( ...
  DryRun = true, ...
  TargetFolder = pwd, ...
  IncludeSubfolders = false, ...
  FileType = "*.m", ...
  Filter = @(x) not(FileTool3.isPlainTextLiveScript(x)), ...
  TextPattern = "function", ...
  IgnoreCase = true );

disp(result) %[output:68a9f945]
%[text] *Copyright 2025 The MathWorks, Inc.*

%[appendix]{"version":"1.0"}
%---
%[metadata:view]
%   data: {"layout":"inline"}
%---
%[output:3a046336]
%   data: {"dataType":"text","outputData":{"text":"C:\\local\\gh-isaacito12-bev\\bev25b\n","truncated":false}}
%---
%[output:82c1d475]
%   data: {"dataType":"text","outputData":{"text":"                <strong>FilePath<\/strong>                <strong>NumReplacedLines<\/strong>\n    <strong>________________________________<\/strong>    <strong>________________<\/strong>\n\n    \"BEVProjectNavigationApp.m\"                1        \n    \"BEVProject_Description.m\"                 1        \n    \"buildfile.m\"                              1        \n    \"uitest_BEVProject.m\"                      1        \n    \"uiuptodatetest_BEVProject.m\"              1        \n    \"unittest_BEVProject.m\"                    1        \n    \"unittest_BEVProject_settings.m\"           1        \n    \"uptodatetest_BEVProject.m\"                1        \n    \"ChangeLog.md\"                             1        \n    \"README.md\"                                1        \n\n","truncated":false}}
%---
%[output:68a9f945]
%   data: {"dataType":"text","outputData":{"text":"                <strong>FilePath<\/strong>                <strong>NumReplacedLines<\/strong>\n    <strong>________________________________<\/strong>    <strong>________________<\/strong>\n\n    \"BEVProjectNavigationApp.m\"                 2       \n    \"buildfile.m\"                               6       \n    \"uitest_BEVProject.m\"                      15       \n    \"uiuptodatetest_BEVProject.m\"              14       \n    \"unittest_BEVProject.m\"                    12       \n    \"unittest_BEVProject_settings.m\"           53       \n    \"uptodatetest_BEVProject.m\"                10       \n\n","truncated":false}}
%---
