function App = bev1mus_TraceGeneratorApp(NameValuePair)

% Copyright 2025-2026 The MathWorks, Inc.

arguments (Input)
  NameValuePair.BlockPath (1,1) string = ""

  NameValuePair.RandomSeed (1,1) string = "4";

  NameValuePair.InitialValue (1,1) string = "0"
  NameValuePair.InitialValueDuration (1,1) string = "10"

  NameValuePair.FirstTransitionDuration (1,1) string = "10"

  NameValuePair.NumberOfTransitions (1,1) string = "2"
  NameValuePair.TransitionDurationRange (1,1) string = "[5, 10]"
  NameValuePair.ConstantDurationRange (1,1) string = "[5, 10]"
  NameValuePair.ValueRange (1,1) string = "[20, 50]"

  NameValuePair.FinalTransitionDuration (1,1) string = "15"

  NameValuePair.FinalValue (1,1) string = "0"
  NameValuePair.FinalValueDuration (1,1) string = "10"
end  % arguments

arguments (Output)
  App bev1mus.SignalUtil.TraceGeneratorAppMain {mustBeScalarOrEmpty}
end  % arguments

app_main = bev1mus.SignalUtil.TraceGeneratorAppMain( ...
  BlockPath = NameValuePair.BlockPath, ...
  RandomSeed = NameValuePair.RandomSeed, ...
  ...
  InitialValue = NameValuePair.InitialValue, ...
  InitialValueDuration = NameValuePair.InitialValueDuration, ...
  ...
  FirstTransitionDuration = NameValuePair.FirstTransitionDuration, ...
  ...
  NumberOfTransitions = NameValuePair.NumberOfTransitions, ...
  TransitionDurationRange = NameValuePair.TransitionDurationRange, ...
  ConstantDurationRange = NameValuePair.ConstantDurationRange, ...
  ValueRange = NameValuePair.ValueRange, ...
  ...
  FinalTransitionDuration = NameValuePair.FinalTransitionDuration, ...
  ...
  FinalValue = NameValuePair.FinalValue, ...
  FinalValueDuration = NameValuePair.FinalValueDuration );

app_main.Window.HeaderUI.AppSourceName = mfilename;

if nargout > 0
  App = app_main;
end  % if
end  % function
