function Result = getCodeCoverageTable(FileName, NameValuePair)
% Get a table containing code coverage from the specified XML file generated by the Build Tool.
%
% This function takes a Cobertura-format code coverage XML file generated by the Build Tool and
% returns a table containing the coverage information where rows are sorted by the coverage value.
%
% This function internally creates a simplified XML file from the specified coverage XML file
% to streamline coverage data processing. By default, the simplified XML file is deleted.
% To keep the simplified XML file, use KeepTempXMLFile=true, and the file is saved in
% the current working folder as "tmp_coverage.xml".

% Copyright 2026 The MathWorks, Inc.

arguments (Input)
  % Code coverage XML file generated by the Build Tool.
  FileName (1,1) string {mustBeFile} = fullfile("test-result", "code-coverage.xml")

  % Names to ignore.
  NameValuePair.IgnoreNamePattern pattern = (textBoundary("start") + "buildfile" + wildcardPattern)

  NameValuePair.OmitCoverageAbove (1,1) {mustBeInRange(NameValuePair.OmitCoverageAbove, 0, 1)} = 1  %#ok<MUSTINRANGE>

  NameValuePair.KeepTempXMLFile (1,1) logical = false
end  % arguments

arguments (Output)
  Result table
end  % arguments

% =============================================================================
% First pass
% Simplify the code coverage XML file, and save the simplified file in another (temporary) file.

lines = readlines(FileName);

logical_index = contains(lines, "<line hits=");
lines = lines(not(logical_index));

logical_index = contains(lines, ("<lines>"|"</lines>"));
lines = lines(not(logical_index));

lines = erase(lines, " branch-rate=""" + alphanumericsPattern + """");
lines = erase(lines, " branches-covered=""" + alphanumericsPattern + """");
lines = erase(lines, " branches-valid=""" + alphanumericsPattern + """");
lines = erase(lines, " complexity=""" + alphanumericsPattern + """");
lines = erase(lines, " version=""" + (alphanumericsPattern|"") + """");

% Example: signature="[out1, out2] = f1(in1, in2)"
lines = erase(lines, " signature=""" + wildcardPattern("Except","""") + """");

lines = replace(lines, " filename=", " FilePath=");
lines = replace(lines, " line-rate=", " LineCoverage=");
lines = replace(lines, " lines-covered=", " LinesCovered=");
lines = replace(lines, " lines-valid=", " LinesValid=");
lines = replace(lines, " name=", " Name=");
lines = replace(lines, " timestamp=", " TimeStamp=");

% Remove the line coverage data from the "package" line.
lines = replace(lines, "<package LineCoverage=""" + wildcardPattern("Except", """") + """ Name=", "<package Name=");

tmpfile = tempname + ".xml";
cleaner = onCleanup(@() on_clean_up(tmpfile));

writelines(lines, tmpfile)

if NameValuePair.KeepTempXMLFile
  covfile_fullpath = fullfile(pwd, "tmp_coverage.xml");
  copyfile(tmpfile, covfile_fullpath)
  disp("Temp XML file: " + covfile_fullpath)
end  % if

% =============================================================================
% Second pass
% Build a table containing the coverage information.

xml_data = readstruct(tmpfile);

num_xml_packages = numel(xml_data.packages.package);

FilePath = string.empty;
Name = string.empty;
LineCoverage = nan(0, 1);
count = 0;
for pp = 1 : num_xml_packages
  xml_package = xml_data.packages.package(pp);

  num_xml_classes = numel(xml_package.classes.class);
  for cc = 1 : num_xml_classes

    xml_class = xml_package.classes.class(cc);

    if isfield(xml_class.methods, "method")
      num_xml_methods = numel(xml_class.methods.method);
      for mm = 1 : num_xml_methods
        xml_method = xml_class.methods.method(mm);
        if xml_method.LineCoverageAttribute > NameValuePair.OmitCoverageAbove

          continue

        end  % if
        count = count + 1;
        FilePath(count, 1) = xml_class.FilePathAttribute;
        Name(count, 1) = xml_method.NameAttribute;
        LineCoverage(count, 1) = xml_method.LineCoverageAttribute;
      end  % for
    else
      if xml_class.LineCoverageAttribute > NameValuePair.OmitCoverageAbove

        continue

      end  % if
      count = count + 1;
      FilePath(count, 1) = xml_class.FilePathAttribute;
      Name(count, 1) = xml_class.NameAttribute;
      LineCoverage(count, 1) = xml_class.LineCoverageAttribute;
    end  % if
  end  % for
end  % for

Result = table(LineCoverage, Name, FilePath);
Result = sortrows(Result, {'LineCoverage', 'Name'}, {'ascend', 'descend'});

time_stamp_posix = xml_data.TimeStampAttribute;
time_stamp_utc = "UTC " + string(datetime(time_stamp_posix, ConvertFrom="posixtime", TimeZone="UTC", Format="yyyy-MM-dd HH:mm:ss"));

top_folder = string(xml_data.sources.source);

Result = addprop(Result, ["TimeStamp", "TopFolder", "OmitCoverageAbove", "LineCoverage", "LinesCovered", "LinesValid"], ...
  ["table", "table", "table", "table", "table", "table"]);
Result.Properties.CustomProperties.TimeStamp = time_stamp_utc;
Result.Properties.CustomProperties.TopFolder = top_folder;
Result.Properties.CustomProperties.OmitCoverageAbove = NameValuePair.OmitCoverageAbove;
Result.Properties.CustomProperties.LineCoverage = xml_data.LineCoverageAttribute;
Result.Properties.CustomProperties.LinesCovered = xml_data.LinesCoveredAttribute;
Result.Properties.CustomProperties.LinesValid = xml_data.LinesValidAttribute;

logical_index = matches(Result.Name, NameValuePair.IgnoreNamePattern);
Result = Result(not(logical_index), :);
end  % function

function on_clean_up(temp_file)
% Avoid using nested functions during cleanup. MATLAB can clear variables used in
% nested functions before the cleanup function tries to read from them.
if isfile(temp_file)
  delete(temp_file)
end  % if
end  % local function
