function Result = getTestResultTable(TestResultFile)
% Get a table containing test result from the specified XML file generated by the Build Tool.
%
% This function takes a JUnit-format test result XML file generated by the Build Tool and
% returns a table containing the test result information.

% Copyright 2026 The MathWorks, Inc.

arguments (Input)
  TestResultFile string {mustBeScalarOrEmpty, mustBeFile}
  % TestResultFile (1,1) string {mustBeFile} = SearchUtil1.searchFiles("sample-test-result-2failures.xml")
end  % arguments

arguments (Output)
  Result table
end  % arguments

xml_data = readstruct(TestResultFile);

% num_xml_testsuites_testclasses = numel(xml_data.testsuite);

% Each row of the table represents a testsuit, which is a unit test class.
xml_testsuites_table = struct2table(xml_data.testsuite);

% Each "testsuite" row in the XML file corresponds to a unit test class.
% A row has "errors", "failures", "name", "skipped", "tests", and "time".
% Within a testsuite, there are one or more "testcase" rows that are unit test functions.
num_total_test_functions = sum(xml_testsuites_table.testsAttribute);
num_total_errors = sum(xml_testsuites_table.errorsAttribute);
num_total_failures = sum(xml_testsuites_table.failuresAttribute);
num_total_skips = sum(xml_testsuites_table.skippedAttribute);
total_test_time = sum(xml_testsuites_table.timeAttribute);

% Table columns
TestClass = strings(num_total_test_functions, 1);
TestFunction = strings(num_total_test_functions, 1);
TestTimeInSeconds = zeros(num_total_test_functions, 1);
TestPassed = false(num_total_test_functions, 1);

test_function_count = 1;
for xml_testsuite_testclass_count = 1 : height(xml_testsuites_table)
  % A "testsuite" row in XML
  if height(xml_testsuites_table) == 1
    xml_testcase_subtable = struct2table(xml_testsuites_table.testcase);
  else
    xml_testcase_subtable = struct2table(xml_testsuites_table.testcase{xml_testsuite_testclass_count});
  end  % if
  num_testcases = xml_testsuites_table.testsAttribute(xml_testsuite_testclass_count);

  TestClass(test_function_count : test_function_count + num_testcases - 1) = xml_testcase_subtable.classnameAttribute;

  for xml_testcase_count = 1 : num_testcases

    TestFunction(test_function_count) = xml_testcase_subtable.nameAttribute(xml_testcase_count);

    TestTimeInSeconds(test_function_count) = double(xml_testcase_subtable.timeAttribute(xml_testcase_count));

    varnames = string(xml_testcase_subtable.Properties.VariableNames);

    if ismember("error", varnames)
      if ismissing(xml_testcase_subtable(xml_testcase_count, "error"))
        TestPassed(test_function_count) = true;
      else
        TestPassed(test_function_count) = false;
      end  % if
    else
      % !todo: This branch may be dead-code.
      TestPassed(test_function_count) = true;
    end  % if

    test_function_count = test_function_count + 1;
  end  % for
end  % for

Result = sortrows(table(TestPassed, TestClass, TestFunction, TestTimeInSeconds), {'TestPassed', 'TestTimeInSeconds'}, {'ascend', 'descend'});

Result = addprop(Result, ...
  ["NumberOfTests", "NumberOfErrors", "NumberOfFailures", "NumberOfSkips", "TotalTestTimeInSeconds", "MeanTestTimeInSeconds", "MedianTestTimeInSeconds"], ...
  ["table",         "table",          "table",            "table",         "table",                  "table",                 "table"]);

Result.Properties.CustomProperties.NumberOfTests = num_total_test_functions;
Result.Properties.CustomProperties.NumberOfErrors = num_total_errors;
Result.Properties.CustomProperties.NumberOfFailures = num_total_failures;
Result.Properties.CustomProperties.NumberOfSkips = num_total_skips;
Result.Properties.CustomProperties.TotalTestTimeInSeconds = total_test_time;
Result.Properties.CustomProperties.MeanTestTimeInSeconds = mean(TestTimeInSeconds);
Result.Properties.CustomProperties.MedianTestTimeInSeconds = median(TestTimeInSeconds);

end  % function
