function fig = Vehicle1D_plotResults(nvpairs)
% plots the simulation result.

% Copyright 2022-2023 The MathWorks, Inc.

arguments
  nvpairs.SimData timetable
  nvpairs.FigureHeight (1,1) {mustBePositive} = 300
end

sigNames = [ ...
  "Axle torque input", ...
  "Brake force", ...
  "Road inclination", ...
  "Road grade", ...
  "G force", ...
  "Vehicle speed kph", ...
  "Vehicle speed mph", ...
  "Axle speed" ];

for i = 1 : numel(sigNames)
  fig = plotSimulationResultSignal(SimData = nvpairs.SimData, SignalName = sigNames(i));
  fig.Position(4) = nvpairs.FigureHeight;
end

end  % function
