function MotorDriveUnit_setRefsub_BasicThermal

% Copyright 2023 The MathWorks, Inc.

MotorDriveUnit_setRefsub( ...
  ModelName = "MotorDriveUnit_TestModel", ...
  BlockPath = "/Motor Drive Unit", ...
  RefsubName    = "MotorDriveUnit_BasicThermal_refsub", ...
  ParamFileName = "MotorDriveUnit_BasicThermal_params" )

end  % function
