function MotorDriveUnit_setRefsub_Basic

% Copyright 2023 The MathWorks, Inc.

MotorDriveUnit_setRefsub( ...
  ModelName = "MotorDriveUnit_TestModel", ...
  BlockPath = "/Motor Drive Unit", ...
  RefsubName    = "MotorDriveUnit_Basic_refsub", ...
  ParamFileName = "MotorDriveUnit_Basic_params" )

end  % function
