function MotorDriveUnit_setRefsub_SystemTable

% Copyright 2023 The MathWorks, Inc.

MotorDriveUnit_setRefsub( ...
  ModelName = "MotorDriveUnit_TestModel", ...
  BlockPath = "/Motor Drive Unit", ...
  RefsubName    = "MotorDriveUnit_SystemTable_refsub", ...
  ParamFileName = "MotorDriveUnit_SystemTable_params" )

end  % function
