function MotorDriveUnit_setRefsub_SystemThermal

% Copyright 2023-2025 The MathWorks, Inc.

MotorDriveUnit_setRefsub( ...
  ModelName = "MotorDriveUnit_TestModel", ...
  BlockPath = "/Motor Drive Unit", ...
  RefsubName = "MotorDriveUnit_SystemThermal_refsub", ...
  ParamFileName = "MotorDriveUnit_SystemThermal_params" )

end  % function
