function MotorDriveUnit_useRefsub_SystemThermal

% Copyright 2023-2025 The MathWorks, Inc.

MotorDriveUnit_setReferencedSubsystem( ...
  ModelName = "MotorDriveUnit_harness_model", ...
  BlockPath = "/Motor Drive Unit", ...
  RefsubName = "MotorDriveUnit_refsub_SystemThermal", ...
  ParamFileName = "MotorDriveUnit_refsub_SystemThermal_params" )

end  % function
