function BatteryHV_loadSimulationCase_Constant
%% Sets up simulation
% This function sets up the followings:
% - Simulation stop time
% - Input signals
% - Initial conditions
%
% Model must be loaded for this function to work.

% Copyright 2023 The MathWorks, Inc.

BatteryHV_loadSimulationCase( ...
  CaseName = "Constant inputs", ...
  ModelName = "BatteryHV_harness_model", ...
  StopTime = 1000, ...
  InputSystemPath = "/Inputs", ...
  LoadCurrentBlockName = "Load current", ...
  LoadCurrentDataPoints = [0 1 0], ...
  LoadCurrentDeltaT = 0.1, ...
  HeatFlowBlockName = "Heat flow", ...
  HeatFlowDataPoints = [0 1 0], ...
  HeatFlowDeltaT = 0.1, ...
  TerminalVoltage_V = evalin("base", "batteryHV.nominalVoltage_V"), ...
  NominalCapacity_kWh = evalin("base", "batteryHV.nominalCapacity_kWh"), ...
  InitialSOC_pct = 50, ...
  InitialBatteryTemperature_K = 273.15 + 20, ...
  InitialAmbientTemperature_K = 273.15 + 20, ...
  DisplayMessage = true );

end  % function
