function BEVController_setRefsub_Basic
%% Sets a specified referenced subsystem to the model
% Model must be loaded before calling this function.

% Copyright 2023 The MathWorks, Inc.

BEVController_setRefsub( ...
  Name = "Basic model", ...
  RefsubName    = "BEVController_Basic_refsub", ...
  ParamFileName = "BEVController_Basic_params", ...
  ...
  ModelName = "BEVController_TestModel", ...
  BlockPath = "/BEV Speed Tracking Controller" )

end  % function
