function CtrlEnv_loadSimulationCase_FTP75(nvpairs)
%% Sets up simulation
% Model must be loaded for this function to work.

% Copyright 2023 The MathWorks, Inc.

arguments
  nvpairs.ModelName {mustBeTextScalar} = "CtrlEnv_harness_model"
  nvpairs.TargetSubsystemPath {mustBeTextScalar} = "/Controller and Environment/Vehicle speed reference"
  nvpairs.DisplayMessage (1,1) logical = true
end

CtrlEnv_loadSimulationCase( ...
  CaseName = "FTP-75 using Drive Cycle Source block", ...
  CaseNumber = 3, ...
  StopTime = 2474, ...
  ...
  ModelName = nvpairs.ModelName, ...
  TargetSubsystemPath = nvpairs.TargetSubsystemPath, ...
  DisplayMessage = nvpairs.DisplayMessage )

end  % function
