%[text] # findTextAndReplace demo
result = FileTool3.findTextAndReplace(...
  DryRun = true, ...
  TopFolder = pwd, ...
  SearchSubfolders = false, ...
  FileType = "*.m", ...
  SearchText = "Copyright" ); 
disp(result) %[output:81d096a1]
%%
result = FileTool3.findTextAndReplace( ...
  DryRun = true, ...
  TopFolder = pwd, ...
  SearchSubfolders = true, ...
  FileType = "get*.m", ...
  SearchText = textBoundary + "Copyright" + textBoundary, ...
  Filter = @(x) FileTool3.isPlainTextLiveScript(x));
disp(result)
%%
result = FileTool3.findTextAndReplace( ...
  DryRun = true, ...
  TopFolder = pwd, ...
  SearchSubfolders = false, ...
  FileType = "*.m", ...
  SearchText = "Copyright", ...
  Filter = @(x) not(FileTool3.isPlainTextLiveScript(x)));
disp(result) %[output:05f9d5a0]
%[text] *Copyright 2025 The MathWorks, Inc.*

%[appendix]{"version":"1.0"}
%---
%[metadata:view]
%   data: {"layout":"inline"}
%---
%[output:81d096a1]
%   data: {"dataType":"text","outputData":{"text":"                               <strong>FilePath<\/strong>                                <strong>LineNumber<\/strong>                         <strong>LineText<\/strong>                      \n    <strong>_______________________________________________________________<\/strong>    <strong>__________<\/strong>    <strong>___________________________________________________<\/strong>\n\n    \"C:\\local\\gh-isaacito12-bev\\bev25a\\BEVProjectNavigationApp.m\"           5        \"% Copyright 2024-2025 The MathWorks, Inc.\"        \n    \"C:\\local\\gh-isaacito12-bev\\bev25a\\BEVProject_Description.m\"           35        \"%[text] *Copyright 2020-2025 The MathWorks, Inc.*\"\n    \"C:\\local\\gh-isaacito12-bev\\bev25a\\buildfile.m\"                        12        \"% Copyright 2023-2025 The MathWorks, Inc.\"        \n    \"C:\\local\\gh-isaacito12-bev\\bev25a\\uitest_BEVProject.m\"                12        \"  % Copyright 2024-2025 The MathWorks, Inc.\"      \n    \"C:\\local\\gh-isaacito12-bev\\bev25a\\uiuptodatetest_BEVProject.m\"        12        \"  % Copyright 2024-2025 The MathWorks, Inc.\"      \n    \"C:\\local\\gh-isaacito12-bev\\bev25a\\unittest_BEVProject.m\"              15        \"  % Copyright 2021-2025 The MathWorks, Inc.\"      \n    \"C:\\local\\gh-isaacito12-bev\\bev25a\\uptodatetest_BEVProject.m\"          15        \"  % Copyright 2021-2025 The MathWorks, Inc.\"      \n\n","truncated":false}}
%---
%[output:05f9d5a0]
%   data: {"dataType":"text","outputData":{"text":"                               <strong>FilePath<\/strong>                                <strong>LineNumber<\/strong>                      <strong>LineText<\/strong>                   \n    <strong>_______________________________________________________________<\/strong>    <strong>__________<\/strong>    <strong>_____________________________________________<\/strong>\n\n    \"C:\\local\\gh-isaacito12-bev\\bev25a\\BEVProjectNavigationApp.m\"           5        \"% Copyright 2024-2025 The MathWorks, Inc.\"  \n    \"C:\\local\\gh-isaacito12-bev\\bev25a\\buildfile.m\"                        12        \"% Copyright 2023-2025 The MathWorks, Inc.\"  \n    \"C:\\local\\gh-isaacito12-bev\\bev25a\\uitest_BEVProject.m\"                12        \"  % Copyright 2024-2025 The MathWorks, Inc.\"\n    \"C:\\local\\gh-isaacito12-bev\\bev25a\\uiuptodatetest_BEVProject.m\"        12        \"  % Copyright 2024-2025 The MathWorks, Inc.\"\n    \"C:\\local\\gh-isaacito12-bev\\bev25a\\unittest_BEVProject.m\"              15        \"  % Copyright 2021-2025 The MathWorks, Inc.\"\n    \"C:\\local\\gh-isaacito12-bev\\bev25a\\uptodatetest_BEVProject.m\"          15        \"  % Copyright 2021-2025 The MathWorks, Inc.\"\n\n","truncated":false}}
%---
