function BatteryHV_useRefsub_SystemLevelTableBased

% Copyright 2023 The MathWorks, Inc.

BatteryHV_useRefsub( ...
  ModelName = "BatteryHV_harness_model", ...
  BlockPath = "/High Voltage Battery", ...
  RefsubName    = "BatteryHV_refsub_SystemLevelTableBased", ...
  ParamFileName = "BatteryHV_refsub_SystemLevelTableBased_params" )

end  % function
