function BatteryHV_useRefsub_Basic

% Copyright 2023 The MathWorks, Inc.

BatteryHV_useRefsub( ...
  ModelName = "BatteryHV_harness_model", ...
  BlockPath = "/High Voltage Battery", ...
  RefsubName    = "BatteryHV_refsub_Basic", ...
  ParamFileName = "BatteryHV_refsub_Basic_params" )

end  % function
