function BatteryHV_useRefsub_SystemLevelSimple

% Copyright 2023 The MathWorks, Inc.

BatteryHV_useRefsub( ...
  ModelName = "BatteryHV_harness_model", ...
  BlockPath = "/High Voltage Battery", ...
  RefsubName    = "BatteryHV_refsub_SystemLevelSimple", ...
  ParamFileName = "BatteryHV_refsub_SystemLevelSimple_params" )

end  % function
