function BEVController_useRefsub_Basic
%% Sets a specified referenced subsystem to the model
% Model must be loaded before calling this function.

% Copyright 2023 The MathWorks, Inc.

BEVController_useRefsub( ...
  Name = "Basic model", ...
  RefsubName    = "BEVController_refsub_Basic", ...
  ParamFileName = "BEVController_refsub_Basic_params", ...
  ...
  ModelName = "BEVController_harness_model", ...
  BlockPath = "/BEV Speed Tracking Controller" )

end  % function
