function fig = CtrlEnv_Vehicle_plotResults(nvpairs)
% plots the simulation result.

% Copyright 2022-2023 The MathWorks, Inc.

arguments
  nvpairs.SimData timetable
  nvpairs.FigureHeight (1,1) {mustBePositive} = 300
end

sigNames = [ ...
  "Brake force", ...
  "Motor torque command", ...
  "Motor heat flow command", ...
  "Battery heat flow command", ...
  "Vehicle speed kph", ...
  "Motor speed", ...
  "Motor temperature", ...
  "Battery temperature" ];

for i = 1 : numel(sigNames)
  fig = plotSimulationResultSignal(SimData = nvpairs.SimData, SignalName = sigNames(i));
  fig.Position(4) = nvpairs.FigureHeight;
end

end  % function
