function MotorDriveUnit_useRefsub_Tabulated

% Copyright 2023 The MathWorks, Inc.

MotorDriveUnit_useRefsub( ...
  ModelName = "MotorDriveUnit_harness_model", ...
  BlockPath = "/Motor Drive Unit", ...
  RefsubName    = "MotorDriveUnit_refsub_Tabulated", ...
  ParamFileName = "MotorDriveUnit_refsub_Tabulated_params" )

end  % function
